"""initial_schema

Revision ID: ed1b5a8cff29
Revises: 
Create Date: 2026-09-18 18:34:20.262835

"""
from alembic import op
import sqlalchemy as sa


revision = 'ed1b5a8cff29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_agents',
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('system_instructions', sa.Text(), nullable=True),
    sa.Column('allowed_tools', sa.JSON(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=False),
    sa.Column('confidence_requirements', sa.Text(), nullable=True),
    sa.Column('evidence_requirements', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DISABLED', name='agentstatus', native_enum=False, length=12), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('max_cost_usd_per_run', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_agents'))
    )
    op.create_index(op.f('ix_ai_agents_agent_id'), 'ai_agents', ['agent_id'], unique=True)
    op.create_table('ai_decisions',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=120), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('applied_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_decisions'))
    )
    op.create_index(op.f('ix_ai_decisions_agent_id'), 'ai_decisions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_ai_decisions_run_id'), 'ai_decisions', ['run_id'], unique=False)
    op.create_table('ai_evidence',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_evidence'))
    )
    op.create_index(op.f('ix_ai_evidence_run_id'), 'ai_evidence', ['run_id'], unique=False)
    op.create_table('ai_runs',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='runstatus', native_enum=False, length=12), nullable=False),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_runs'))
    )
    op.create_index(op.f('ix_ai_runs_agent_id'), 'ai_runs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_status'), 'ai_runs', ['status'], unique=False)
    op.create_index(op.f('ix_ai_runs_ticket_id'), 'ai_runs', ['ticket_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('before', sa.JSON(), nullable=False),
    sa.Column('after', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('change_requests',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('impact_analysis', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'PLAN_READY', 'APPROVED', 'REJECTED', 'APPLIED', 'ROLLED_BACK', name='changerequeststatus', native_enum=False, length=14), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rollback_ref', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_requests'))
    )
    op.create_index(op.f('ix_change_requests_status'), 'change_requests', ['status'], unique=False)
    op.create_table('companies',
    sa.Column('legal_name', sa.String(length=300), nullable=False),
    sa.Column('trade_name', sa.String(length=300), nullable=True),
    sa.Column('website', sa.String(length=1000), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('size_band', sa.String(length=32), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=False)
    op.create_index(op.f('ix_companies_legal_name'), 'companies', ['legal_name'], unique=False)
    op.create_table('consent_records',
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('GRANTED', 'WITHDRAWN', name='consentstatus', native_enum=False, length=12), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent_records'))
    )
    op.create_index(op.f('ix_consent_records_contact_id'), 'consent_records', ['contact_id'], unique=False)
    op.create_table('email_verifications',
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('syntax_ok', sa.Boolean(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('mx_present', sa.Boolean(), nullable=True),
    sa.Column('is_disposable', sa.Boolean(), nullable=False),
    sa.Column('is_catch_all', sa.Boolean(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verifications'))
    )
    op.create_index(op.f('ix_email_verifications_email'), 'email_verifications', ['email'], unique=False)
    op.create_index(op.f('ix_email_verifications_record_id'), 'email_verifications', ['record_id'], unique=False)
    op.create_table('identity_verifications',
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('contact_ref', sa.String(length=36), nullable=False),
    sa.Column('profile_url', sa.String(length=1000), nullable=True),
    sa.Column('company_website_match', sa.Boolean(), nullable=True),
    sa.Column('public_source_consistency', sa.String(length=32), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_verifications'))
    )
    op.create_index(op.f('ix_identity_verifications_contact_ref'), 'identity_verifications', ['contact_ref'], unique=False)
    op.create_index(op.f('ix_identity_verifications_record_id'), 'identity_verifications', ['record_id'], unique=False)
    op.create_table('intent_score_snapshots',
    sa.Column('kind', sa.Enum('LEAD', 'INTENT', 'RISK', name='scorekind', native_enum=False, length=8), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('computed_by', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intent_score_snapshots'))
    )
    op.create_index(op.f('ix_intent_score_snapshots_ticket_id'), 'intent_score_snapshots', ['ticket_id'], unique=False)
    op.create_table('jobs',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_name'), 'jobs', ['name'], unique=True)
    op.create_table('lead_score_snapshots',
    sa.Column('kind', sa.Enum('LEAD', 'INTENT', 'RISK', name='scorekind', native_enum=False, length=8), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('computed_by', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_score_snapshots'))
    )
    op.create_index(op.f('ix_lead_score_snapshots_ticket_id'), 'lead_score_snapshots', ['ticket_id'], unique=False)
    op.create_table('permissions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('phone_verifications',
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('is_valid_format', sa.Boolean(), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('carrier', sa.String(length=120), nullable=True),
    sa.Column('line_type', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone_verifications'))
    )
    op.create_index(op.f('ix_phone_verifications_phone'), 'phone_verifications', ['phone'], unique=False)
    op.create_index(op.f('ix_phone_verifications_record_id'), 'phone_verifications', ['record_id'], unique=False)
    op.create_table('qa_findings',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='findingseverity', native_enum=False, length=10), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('root_cause_hypothesis', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('affected_component', sa.String(length=120), nullable=True),
    sa.Column('test_recommendation', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED', name='findingstatus', native_enum=False, length=14), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qa_findings'))
    )
    op.create_index(op.f('ix_qa_findings_category'), 'qa_findings', ['category'], unique=False)
    op.create_index(op.f('ix_qa_findings_run_id'), 'qa_findings', ['run_id'], unique=False)
    op.create_index(op.f('ix_qa_findings_severity'), 'qa_findings', ['severity'], unique=False)
    op.create_index(op.f('ix_qa_findings_status'), 'qa_findings', ['status'], unique=False)
    op.create_table('qa_reports',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qa_reports'))
    )
    op.create_index(op.f('ix_qa_reports_run_id'), 'qa_reports', ['run_id'], unique=False)
    op.create_table('qa_runs',
    sa.Column('trigger', sa.Enum('MANUAL', 'SCHEDULED', 'WEBHOOK', name='qatrigger', native_enum=False, length=12), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qa_runs'))
    )
    op.create_table('risk_score_snapshots',
    sa.Column('kind', sa.Enum('LEAD', 'INTENT', 'RISK', name='scorekind', native_enum=False, length=8), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('computed_by', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_score_snapshots'))
    )
    op.create_index(op.f('ix_risk_score_snapshots_ticket_id'), 'risk_score_snapshots', ['ticket_id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('sources',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=120), nullable=True),
    sa.Column('kind', sa.Enum('API', 'PUBLIC_WEB', 'FEED', 'LICENSED_DATASET', 'SEARCH', 'MARKETPLACE', 'USER_INTEGRATION', 'MANUAL', name='sourcekind', native_enum=False, length=20), nullable=False),
    sa.Column('base_url', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('compliance_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=True)
    op.create_table('suppression_records',
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=320), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppression_records'))
    )
    op.create_index(op.f('ix_suppression_records_contact_id'), 'suppression_records', ['contact_id'], unique=False)
    op.create_index(op.f('ix_suppression_records_value'), 'suppression_records', ['value'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('ticket_categories',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('marketplace_domain', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_categories'))
    )
    op.create_index(op.f('ix_ticket_categories_code'), 'ticket_categories', ['code'], unique=True)
    op.create_table('ticket_statuses',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_statuses'))
    )
    op.create_index(op.f('ix_ticket_statuses_code'), 'ticket_statuses', ['code'], unique=True)
    op.create_table('ticket_types',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_types'))
    )
    op.create_index(op.f('ix_ticket_types_code'), 'ticket_types', ['code'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('verification_records',
    sa.Column('entity_kind', sa.Enum('EMAIL', 'PHONE', 'COMPANY', 'DIGITAL_IDENTITY', name='verificationkind', native_enum=False, length=20), nullable=False),
    sa.Column('entity_ref', sa.String(length=320), nullable=False),
    sa.Column('kind', sa.Enum('EMAIL', 'PHONE', 'COMPANY', 'DIGITAL_IDENTITY', name='verificationkind', native_enum=False, length=20), nullable=False),
    sa.Column('result', sa.Enum('VERIFIED', 'FAILED', 'UNVERIFIABLE', 'UNKNOWN', name='verificationresult', native_enum=False, length=14), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=120), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_records'))
    )
    op.create_index(op.f('ix_verification_records_entity_kind'), 'verification_records', ['entity_kind'], unique=False)
    op.create_index(op.f('ix_verification_records_entity_ref'), 'verification_records', ['entity_ref'], unique=False)
    op.create_index(op.f('ix_verification_records_result'), 'verification_records', ['result'], unique=False)
    op.create_table('webhook_events',
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('signature_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events'))
    )
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_source'), 'webhook_events', ['source'], unique=False)
    op.create_index(op.f('ix_webhook_events_status'), 'webhook_events', ['status'], unique=False)
    op.create_table('company_domains',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_official_website', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_domains_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_domains'))
    )
    op.create_index(op.f('ix_company_domains_company_id'), 'company_domains', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_domains_domain'), 'company_domains', ['domain'], unique=False)
    op.create_table('contacts',
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('work_email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('profile_url', sa.String(length=1000), nullable=True),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_contacts_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_contacts_full_name'), 'contacts', ['full_name'], unique=False)
    op.create_index(op.f('ix_contacts_phone'), 'contacts', ['phone'], unique=False)
    op.create_index(op.f('ix_contacts_work_email'), 'contacts', ['work_email'], unique=False)
    op.create_table('job_runs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus', native_enum=False, length=12), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_runs_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_runs'))
    )
    op.create_index(op.f('ix_job_runs_job_id'), 'job_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_runs_status'), 'job_runs', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', 'SMS', 'WEBHOOK', name='notificationchannel', native_enum=False, length=10), nullable=False),
    sa.Column('type', sa.Enum('TICKET_UPDATE', 'HANDOVER', 'VERIFICATION', 'QA_ALERT', 'CONNECTOR_ALERT', 'SYSTEM', name='notificationtype', native_enum=False, length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('ticket_id', sa.String(length=36), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_ticket_id'), 'notifications', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name=op.f('uq_role_permissions_role_id'))
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('source_connectors',
    sa.Column('connector_id', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('auth_method', sa.Enum('NONE', 'API_KEY', 'OAUTH2', 'BASIC', 'BEARER', 'WEBHOOK_SIGNATURE', name='authmethod', native_enum=False, length=20), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('health', sa.Enum('HEALTHY', 'DEGRADED', 'DOWN', 'UNKNOWN', name='connectorhealth', native_enum=False, length=12), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_connectors_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_connectors'))
    )
    op.create_index(op.f('ix_source_connectors_connector_id'), 'source_connectors', ['connector_id'], unique=True)
    op.create_index(op.f('ix_source_connectors_source_id'), 'source_connectors', ['source_id'], unique=False)
    op.create_index(op.f('ix_source_connectors_status'), 'source_connectors', ['status'], unique=False)
    op.create_table('source_records',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('connector_run_id', sa.String(length=36), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('is_consumed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_records_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_records'))
    )
    op.create_index(op.f('ix_source_records_connector_run_id'), 'source_records', ['connector_run_id'], unique=False)
    op.create_index(op.f('ix_source_records_external_id'), 'source_records', ['external_id'], unique=False)
    op.create_index(op.f('ix_source_records_source_id'), 'source_records', ['source_id'], unique=False)
    op.create_table('tickets',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('type_id', sa.String(length=36), nullable=False),
    sa.Column('status_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('domain', sa.String(length=120), nullable=True),
    sa.Column('market_sector', sa.String(length=120), nullable=True),
    sa.Column('product', sa.String(length=200), nullable=True),
    sa.Column('service', sa.String(length=200), nullable=True),
    sa.Column('requirement', sa.Text(), nullable=True),
    sa.Column('requirement_details', sa.JSON(), nullable=False),
    sa.Column('intent_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='intentlevel', native_enum=False, length=16), nullable=True),
    sa.Column('urgency', sa.String(length=32), nullable=True),
    sa.Column('budget', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('deal_size', sa.String(length=32), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('jurisdiction', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('pain_point', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=120), nullable=True),
    sa.Column('platform_url', sa.String(length=1000), nullable=True),
    sa.Column('original_url', sa.String(length=1000), nullable=True),
    sa.Column('official_website_url', sa.String(length=1000), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_by', sa.String(length=200), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('intent_score', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'PENDING', 'VERIFIED', 'FAILED', 'STALE', 'UNKNOWN', name='verificationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('freshness', sa.Enum('FRESH', 'AGING', 'STALE', name='freshness', native_enum=False, length=12), nullable=False),
    sa.Column('duplicate_status', sa.Enum('UNIQUE', 'POSSIBLE_DUPLICATE', 'DUPLICATE', 'MERGED', name='duplicatestatus', native_enum=False, length=20), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('intent_score BETWEEN 0 AND 100', name='intent_score_range'),
    sa.CheckConstraint('lead_score BETWEEN 0 AND 100', name='lead_score_range'),
    sa.CheckConstraint('risk_score BETWEEN 0 AND 100', name='risk_score_range'),
    sa.ForeignKeyConstraint(['category_id'], ['ticket_categories.id'], name=op.f('fk_tickets_category_id_ticket_categories')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_tickets_owner_id_users')),
    sa.ForeignKeyConstraint(['status_id'], ['ticket_statuses.id'], name=op.f('fk_tickets_status_id_ticket_statuses')),
    sa.ForeignKeyConstraint(['type_id'], ['ticket_types.id'], name=op.f('fk_tickets_type_id_ticket_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets'))
    )
    op.create_index(op.f('ix_tickets_category_id'), 'tickets', ['category_id'], unique=False)
    op.create_index(op.f('ix_tickets_domain'), 'tickets', ['domain'], unique=False)
    op.create_index(op.f('ix_tickets_duplicate_status'), 'tickets', ['duplicate_status'], unique=False)
    op.create_index(op.f('ix_tickets_location'), 'tickets', ['location'], unique=False)
    op.create_index(op.f('ix_tickets_market_sector'), 'tickets', ['market_sector'], unique=False)
    op.create_index(op.f('ix_tickets_owner_id'), 'tickets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_tickets_platform'), 'tickets', ['platform'], unique=False)
    op.create_index(op.f('ix_tickets_reference'), 'tickets', ['reference'], unique=True)
    op.create_index(op.f('ix_tickets_status_id'), 'tickets', ['status_id'], unique=False)
    op.create_index(op.f('ix_tickets_type_id'), 'tickets', ['type_id'], unique=False)
    op.create_index(op.f('ix_tickets_verification_status'), 'tickets', ['verification_status'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles'))
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=True)
    op.create_table('connector_runs',
    sa.Column('connector_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus', native_enum=False, length=12), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_found', sa.Integer(), nullable=False),
    sa.Column('tickets_created', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['source_connectors.id'], name=op.f('fk_connector_runs_connector_id_source_connectors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector_runs'))
    )
    op.create_index(op.f('ix_connector_runs_connector_id'), 'connector_runs', ['connector_id'], unique=False)
    op.create_index(op.f('ix_connector_runs_status'), 'connector_runs', ['status'], unique=False)
    op.create_table('contact_emails',
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_contact_emails_contact_id_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_emails'))
    )
    op.create_index(op.f('ix_contact_emails_contact_id'), 'contact_emails', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_emails_email'), 'contact_emails', ['email'], unique=False)
    op.create_table('contact_phones',
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_contact_phones_contact_id_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_phones'))
    )
    op.create_index(op.f('ix_contact_phones_contact_id'), 'contact_phones', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_phones_phone'), 'contact_phones', ['phone'], unique=False)
    op.create_table('conversations',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_conversations_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_conversations_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('ticket_id', 'contact_id', name=op.f('uq_conversations_ticket_id'))
    )
    op.create_index(op.f('ix_conversations_ticket_id'), 'conversations', ['ticket_id'], unique=False)
    op.create_table('ticket_companies',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('PRIMARY', 'RELATED', name='ticketcompanyrole', native_enum=False, length=12), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_ticket_companies_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_companies_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_companies'))
    )
    op.create_index(op.f('ix_ticket_companies_company_id'), 'ticket_companies', ['company_id'], unique=False)
    op.create_index(op.f('ix_ticket_companies_ticket_id'), 'ticket_companies', ['ticket_id'], unique=False)
    op.create_table('ticket_contacts',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('PRIMARY', 'DECISION_MAKER', 'INFLUENCER', 'CC', name='ticketcontactrole', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_ticket_contacts_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_contacts_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_contacts'))
    )
    op.create_index(op.f('ix_ticket_contacts_contact_id'), 'ticket_contacts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_ticket_contacts_ticket_id'), 'ticket_contacts', ['ticket_id'], unique=False)
    op.create_table('ticket_sources',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_ticket_sources_source_id_sources'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_sources_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_sources'))
    )
    op.create_index(op.f('ix_ticket_sources_source_id'), 'ticket_sources', ['source_id'], unique=False)
    op.create_index(op.f('ix_ticket_sources_source_record_id'), 'ticket_sources', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_ticket_sources_ticket_id'), 'ticket_sources', ['ticket_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.String(length=12), nullable=False),
    sa.Column('sender', sa.String(length=320), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_messages'))
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_ticket_sources_ticket_id'), table_name='ticket_sources')
    op.drop_index(op.f('ix_ticket_sources_source_record_id'), table_name='ticket_sources')
    op.drop_index(op.f('ix_ticket_sources_source_id'), table_name='ticket_sources')
    op.drop_table('ticket_sources')
    op.drop_index(op.f('ix_ticket_contacts_ticket_id'), table_name='ticket_contacts')
    op.drop_index(op.f('ix_ticket_contacts_contact_id'), table_name='ticket_contacts')
    op.drop_table('ticket_contacts')
    op.drop_index(op.f('ix_ticket_companies_ticket_id'), table_name='ticket_companies')
    op.drop_index(op.f('ix_ticket_companies_company_id'), table_name='ticket_companies')
    op.drop_table('ticket_companies')
    op.drop_index(op.f('ix_conversations_ticket_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_contact_phones_phone'), table_name='contact_phones')
    op.drop_index(op.f('ix_contact_phones_contact_id'), table_name='contact_phones')
    op.drop_table('contact_phones')
    op.drop_index(op.f('ix_contact_emails_email'), table_name='contact_emails')
    op.drop_index(op.f('ix_contact_emails_contact_id'), table_name='contact_emails')
    op.drop_table('contact_emails')
    op.drop_index(op.f('ix_connector_runs_status'), table_name='connector_runs')
    op.drop_index(op.f('ix_connector_runs_connector_id'), table_name='connector_runs')
    op.drop_table('connector_runs')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_tickets_verification_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_type_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_reference'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_platform'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_owner_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_market_sector'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_location'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_duplicate_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_domain'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_category_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_source_records_source_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_external_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_connector_run_id'), table_name='source_records')
    op.drop_table('source_records')
    op.drop_index(op.f('ix_source_connectors_status'), table_name='source_connectors')
    op.drop_index(op.f('ix_source_connectors_source_id'), table_name='source_connectors')
    op.drop_index(op.f('ix_source_connectors_connector_id'), table_name='source_connectors')
    op.drop_table('source_connectors')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_ticket_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_job_runs_status'), table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_job_id'), table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index(op.f('ix_contacts_work_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_phone'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_full_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_company_domains_domain'), table_name='company_domains')
    op.drop_index(op.f('ix_company_domains_company_id'), table_name='company_domains')
    op.drop_table('company_domains')
    op.drop_index(op.f('ix_webhook_events_status'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_source'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_verification_records_result'), table_name='verification_records')
    op.drop_index(op.f('ix_verification_records_entity_ref'), table_name='verification_records')
    op.drop_index(op.f('ix_verification_records_entity_kind'), table_name='verification_records')
    op.drop_table('verification_records')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ticket_types_code'), table_name='ticket_types')
    op.drop_table('ticket_types')
    op.drop_index(op.f('ix_ticket_statuses_code'), table_name='ticket_statuses')
    op.drop_table('ticket_statuses')
    op.drop_index(op.f('ix_ticket_categories_code'), table_name='ticket_categories')
    op.drop_table('ticket_categories')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_suppression_records_value'), table_name='suppression_records')
    op.drop_index(op.f('ix_suppression_records_contact_id'), table_name='suppression_records')
    op.drop_table('suppression_records')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_risk_score_snapshots_ticket_id'), table_name='risk_score_snapshots')
    op.drop_table('risk_score_snapshots')
    op.drop_table('qa_runs')
    op.drop_index(op.f('ix_qa_reports_run_id'), table_name='qa_reports')
    op.drop_table('qa_reports')
    op.drop_index(op.f('ix_qa_findings_status'), table_name='qa_findings')
    op.drop_index(op.f('ix_qa_findings_severity'), table_name='qa_findings')
    op.drop_index(op.f('ix_qa_findings_run_id'), table_name='qa_findings')
    op.drop_index(op.f('ix_qa_findings_category'), table_name='qa_findings')
    op.drop_table('qa_findings')
    op.drop_index(op.f('ix_phone_verifications_record_id'), table_name='phone_verifications')
    op.drop_index(op.f('ix_phone_verifications_phone'), table_name='phone_verifications')
    op.drop_table('phone_verifications')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_lead_score_snapshots_ticket_id'), table_name='lead_score_snapshots')
    op.drop_table('lead_score_snapshots')
    op.drop_index(op.f('ix_jobs_name'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_intent_score_snapshots_ticket_id'), table_name='intent_score_snapshots')
    op.drop_table('intent_score_snapshots')
    op.drop_index(op.f('ix_identity_verifications_record_id'), table_name='identity_verifications')
    op.drop_index(op.f('ix_identity_verifications_contact_ref'), table_name='identity_verifications')
    op.drop_table('identity_verifications')
    op.drop_index(op.f('ix_email_verifications_record_id'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_email'), table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index(op.f('ix_consent_records_contact_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_companies_legal_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_change_requests_status'), table_name='change_requests')
    op.drop_table('change_requests')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_runs_ticket_id'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_status'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_agent_id'), table_name='ai_runs')
    op.drop_table('ai_runs')
    op.drop_index(op.f('ix_ai_evidence_run_id'), table_name='ai_evidence')
    op.drop_table('ai_evidence')
    op.drop_index(op.f('ix_ai_decisions_run_id'), table_name='ai_decisions')
    op.drop_index(op.f('ix_ai_decisions_agent_id'), table_name='ai_decisions')
    op.drop_table('ai_decisions')
    op.drop_index(op.f('ix_ai_agents_agent_id'), table_name='ai_agents')
    op.drop_table('ai_agents')
    # ### end Alembic commands ###
